In [1]:
import numpy as np  
import pandas as pd

In [2]:
df = pd.read_csv("Retail_Data.csv")

In [3]:
df

,Unnamed: 0,geo,channel,brand,SKU,month,year,scenario,volume,Region Name,Market Name,Category
0,0,Australia,Offline,Brand_2,SKU_1,2017-01-01,2017,historical,0.000000,Asia Pacific,Australia,Category_1
1,1,Australia,Offline,Brand_2,SKU_1,2017-02-01,2017,historical,0.000000,Asia Pacific,Australia,Category_1
2,2,Australia,Offline,Brand_2,SKU_1,2017-03-01,2017,historical,0.000000,Asia Pacific,Australia,Category_1
3,3,Australia,Offline,Brand_2,SKU_1,2017-04-01,2017,historical,0.000000,Asia Pacific,Australia,Category_1
4,4,Australia,Offline,Brand_2,SKU_1,2017-05-01,2017,historical,0.000000,Asia Pacific,Australia,Category_1
...,...,...,...,...,...,...,...,...,...,...,...,...
319693,527254,Uruguay,Online,Brand_21,SKU_1,2026-02-01,2026,forecasted,55.294389,Latin America,South LAC,Category_1
319694,527257,Uruguay,Online,Brand_21,SKU_1,2026-03-01,2026,forecasted,36.045882,Latin America,South LAC,Category_1
319695,527260,Uruguay,Online,Brand_21,SKU_1,2026-04-01,2026,forecasted,40.085559,Latin America,South LAC,Category_1
319696,527263,Uruguay,Online,Brand_21,SKU_1,2026-05-01,2026,forecasted,50.782292,Latin America,South LAC,Category_1
319697,527266,Uruguay,Online,Brand_21,SKU_1,2026-06-01,2026,forecasted,45.569634,Latin America,South LAC,Category_1

In [5]:
import streamlit as st
def sum(a,b):
    return a+b
sum(5,3)
st.write(sum(5,3))

2023-09-02 18:58:29.430
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/rahulkushwaha/anaconda3/envs/genai/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]